### ISSUE TITLE
Roadmap: 1.3.3

### ISSUE THREAD

**Issue by DynamicThijs** [DynamicThijs/KeepChunks#2]
This is a list of bugs to be fixed/changes to be made in the 1.3.3 release.

- [x] Remove "You are running the latest version" message
- [x] Load after Multiverse-Core and other multiworld plugins
- [x] Fix some debug messages appearing with debug mode disabled.
- [x] Fix double chunk loading

Feel free to suggest new features/report bugs, to do so, click [here](https://github.com/DynamicThijs/KeepChunks/issues/new)!
