### ISSUE TITLE
Roadmap: 1.3.4

### ISSUE THREAD

**Issue by DynamicThijs** [DynamicThijs/KeepChunks#3]
This is a list of bugs to be fixed/changes to be made in the 1.3.4 release.

- [x] Suppress updater errors, as they're mostly the fault of the users.
- [x] Dynamic load option
- [x] Merge /kc kcm/rcm and /kc kc/rc into 1 command

Feel free to suggest new features/report bugs, to do so, click [here](https://github.com/DynamicThijs/KeepChunks/issues/new)!
